### ISSUE TITLE
Move repo to lab-grid/labflow

### ISSUE THREAD

**Issue by kathryn-explorable** [explorablelabs/labflow#11]
I just mirrored it, but I'm realizing it's not trivial to move over Projects/Issues.

So I can redo this end of the week, whenever there will be a day of no updates...

**Comment by kathryn-explorable** [comment]
I moved this whole repo over to https://github.com/lab-grid/labflow/
I copied all issues and set up the projects the same way they are here.
Things that I didn't copy: 3 closed pull requests, issues are not linked to commits.

**Comment by kathryn-explorable** [comment]
@robotoer I'm going to close this... I tested the new lab-grid/labflow repo... it works.
It has all the code, project cards, and issues that this one does.
I think it's ok that issues are not linked to commits, and pull requests are missing. 
I'll leave this repo open for a bit just to in case I missed something, but otherwise future work should be in lab-grid/labflow. Thanks!

**Comment by robotoer** [comment]
Awesome! Thanks Kathryn
